### ISSUE TITLE
Can't change StatusBar backgroundColor

### ISSUE THREAD

**Issue by vTrip** [react-native-community/react-native-safe-area-view#10]
Applying the `backgroundColor` prop to StatusBar component doesn't get applied. I need to set the background colour of SafeAreaView to get the effect i want, which is not desired because on iPhone X it will have that same colour at the bottom of the screen where the "notch" is

**Comment by emilefleming** [comment]
@vTrip `backgroundColor` prop for StatusBar in React Native is only supported on Android and not on iOS unfortunately, you will need to find another way.

https://facebook.github.io/react-native/docs/statusbar.html#backgroundcolor

**Comment by gpawlik** [comment]
@vTrip Could you please share with us your workaround for this issue?
