### ISSUE TITLE
Duplicate Module Warn: Hope to upgrade `hoist-non-react-statics` to the latest version.

### ISSUE THREAD

**Issue by anchengjian** [react-native-community/react-native-safe-area-view#100]
# Bug

Library version: <= 1.0.0 

## Steps To Reproduce

When I use react-redux, I will be reminded that the module duplicated

![image](https://user-images.githubusercontent.com/8679331/68663188-32d19880-0579-11ea-8624-f60d966a714b.png)

![image](https://user-images.githubusercontent.com/8679331/68663220-3ebd5a80-0579-11ea-82fc-b534e4ff1814.png)

## Reproducible sample code

Hope to upgrade `hoist-non-react-statics` to the latest version.

**Comment by brentvatne** [comment]
you should use a more recent version of react-native that removes haste. i guess you are on an older version :) this won't be a problem then.
