### ISSUE TITLE
Enzyme.mount fails with SafeAreaView and SafeAreaProvider

### ISSUE THREAD

**Issue by elizabethvenner** [react-native-community/react-native-safe-area-view#104]
Hi,
We're attempting to use react-native-safe-area-view/-context and it's working well in the running app, but some of our tests are failing. Specifically, the failing tests are the ones where we try to perform an Enzyme.mount() of a component that uses the SafeAreaView. Initially these fail with:

"'<SafeAreaView /> must be wrapped by react-native-safe-area-context <SafeAreaProvider />'"

If we try to wrap the mounted component in a SafeAreaProvider, the ReactWrapper that comes back no longer finds any of the expected components.

Example:

```
const store = MockStore(state)

    const wrapper = Enzyme.mount(
      <Provider store={store}>
        <SafeAreaProvider>
          <SomeComponent/>
        </SafeAreaProvider>
      </Provider>
    )

    expect(wrapper.find(SomeOtherComponent)).to.have.length(4)
```

Without the SafeAreaProvider, and if we remove the SafeAreaView in SomeComponent, the test passes as expected. Can you offer some guidance on how to setup a test like this?

**Comment by hombrew** [comment]
hello @elizabethvenner, were you able to solve this?
i'm having the exact same problem.

**Comment by DnEgorWeb** [comment]
Does this package have any support still? Looks like last 10+ issues are open or self closed.
@elizabethvenner  @hombrew have you found a decision?

**Comment by DnEgorWeb** [comment]
I found a solution here #https://github.com/th3rdwave/react-native-safe-area-context/issues/31
I think it would be great if documentation had a line about it, because the solution for the problem is not obvious at all.
Solution itself: add to your SafeAreaProvider prop initialSafeAreaInsets. After that mount magically renders all nested components.
```
<SafeAreaProvider initialSafeAreaInsets={{ top: 1, left: 2, right: 3, bottom: 4 }}>
  <YourComponentYouAreSufferingToTest />
</SafeAreaProvider>
```

**Comment by alexborton** [comment]
> <SafeAreaProvider initialSafeAreaInsets={{ top: 1, left: 2, right: 3, bottom: 4 }}>

This is correct and works - nice find.

I also started mocking both the `view` and `context` if anyone prefers that approach;

```
jest.mock(
  'react-native-safe-area-view',
  () =>
    class MockSafeAreaView extends React.Component {
      render() {
        const { children } = this.props
        return React.createElement('SafeAreaView', this.props, children)
      }
    },
)

jest.mock('react-native-safe-area-context', () => ({
  useSafeArea: () => ({ insets: null }),
}))
```

**Comment by schumannd** [comment]
@alexborton 

Your approach results in 

    babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
    Invalid variable access: React

Can you give additional info on how and where you deploy that code? Do you copy/paste it into every test?

I got it running by creating the file:

__mocks__/react-native-safe-area-view.js:

    const React = require('react');
    type Props = { children: any };
    const safeAreaMockRenderFunction = ({ children, ...otherProps }: Props) => {
      return React.createElement('SafeAreaView', otherProps, children);
    };
    export default safeAreaMockRenderFunction;

**Comment by alexborton** [comment]
@schumannd I simply placed this in my `setup.js` file that is referenced by jest config file. I imagine yours is quite different based on whatever setup you have but;

`package.json -> jestconfig.json -> setup.json` 

That's a rough idea of the structure and reference i have. 

I am not familiar with your error i'm afraid

**Comment by brentvatne** [comment]
this library is deprecated, use react-native-safe-area-context instead :)
