### ISSUE TITLE
Remove example folder from npm 

### ISSUE THREAD

**Issue by retyui** [react-native-community/react-native-safe-area-view#106]
# Bug
Could you ignore an `example` folder when publish a package?

![image](https://user-images.githubusercontent.com/4661784/75393526-4eca3180-58ff-11ea-9ed9-785707edaab4.png)

## Environment info

Library version: [1.0.0](https://unpkg.com/browse/react-native-safe-area-view@1.0.0/lib/typescript/)

**Comment by brentvatne** [comment]
it's not included anymore: https://github.com/react-navigation/react-native-safe-area-view/blob/cfa654c8a4504b259a9334aa3743b8088cc55f49/package.json#L22-L25
