### ISSUE TITLE
EventEmitter for safe area insets changing 

### ISSUE THREAD

**Issue by retyui** [react-native-community/react-native-safe-area-view#107]
# Feature Request

```js
import { NativeModules, NativeEventEmitter } from "react-native";
export const { RNSafeArea } = NativeModules;
const nativeEventEmitter = new NativeEventEmitter(RNSafeArea);

nativeEventEmitter.addListener("insetsChanged", insets => {
  console.log(" --- ", insets);
});
```

## Why it is needed

To get ability use save area insets value without rendering `<RNCSaveArea/>`

## Possible implementation

...

### Code sample

see above...

**Comment by brentvatne** [comment]
i'm not convinced that this is necessary. you can use `react-native-safe-area-context` to get this with hooks or context and it seems to be better than re-exporting it in safe-area-view https://github.com/th3rdwave/react-native-safe-area-context
