### ISSUE TITLE
Calling 'getNode()' on the ref of Animated component is no longer necessary

### ISSUE THREAD

**Issue by izniburak** [react-native-community/react-native-safe-area-view#111]
# Question
I just upgrade my react native application to 0.62.0, and now my app keeps getting this warning box
```
ReactNativeFiberHostComponent: Calling `getNode()` on the ref of an Animated component 
is no longer necessary. You can now directly use the ref instead. 
This method will be removed in a future release.
```
I'm using `react-native-safe-area-context (^0.7.3)` and `react-native-safe-area-view (^1.0.0)`. Probably, reason of this problem is react-native-safe-area-view. Because this library is using Animated component with getNode() method sign in AnimatedView interface. 

You can check out [this post](https://reactnative.dev/blog/2020/03/26/version-0.62#deprecations) for 0.62 references.

Do you have any suggestion about that?

## Project Info
```
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 50.71 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 22, 23, 26, 27, 28
      Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by yarikpwnzer** [comment]
Same, we want to release 0.62 ASAP because of text input issues on older RN versions. We just waiting this library update.

**Comment by msvargas** [comment]
I fix with patch-package:

share my react-native-safe-area-view+1.0.0.patch
```patch

diff --git a/node_modules/react-native-safe-area-view/src/index.tsx b/node_modules/react-native-safe-area-view/src/index.tsx
index b42f27f..2e11885 100644
--- a/node_modules/react-native-safe-area-view/src/index.tsx
+++ b/node_modules/react-native-safe-area-view/src/index.tsx
@@ -104,7 +104,6 @@ export default class SafeAreaView extends React.Component<Props, State> {
     const { width: WIDTH, height: HEIGHT } = getResolvedDimensions();
 
     this._view.current
-      .getNode()
       .measureInWindow((realX, realY, winWidth, winHeight) => {
         if (!this._view.current) {
           return;


```

**Comment by mystic001** [comment]
how can i fix the getnode on the ref of animated component is no longer neccesary

**Comment by brentvatne** [comment]
a fix for react-native@0.62 is available in react-native-safe-area-view@1.1.0! thanks for the report!

**Comment by schumannd** [comment]
I am a bit confused, maybe someone in this thread can explain to me the interactions of github, npm and the react-native-community repo:


1. ReactNativeView seems to be [part of react native 0.62 ](https://reactnative.dev/docs/safeareaview). If I import SafeAreaView from react-native, which version am I using? How do I check this? Is the code duplicated somewhere else, or pulled from this react-native-community repo?

2. Version 1.1.0 does not appear when checking [the "releases" tab on github](https://github.com/react-native-community/react-native-safe-area-view/releases).  Neither does version 1.0.0 the latest is 0.14.6. But [when checkin e.g. npmjs the latest version is listed as 1.1.0](https://www.npmjs.com/package/react-native-safe-area-view). How and where are these versions defined? I checked the tags, it's not defined there. I checked the commits: there is one commit mentioning version 1.0.0. No commit even mentions 1.1.0. How can I see which commits are included in which version, and how are version releases generally handled when dealing with npm, github etc?

3. This question might be answered when the former questions are answered, but as it is the source of my troubles: In what case do I need to install this package separately? Especially the react-native-safe-area-context one. It seems to be not needed by the version included in RN 0.62

Thanks in advance.

**Comment by brentvatne** [comment]
1. this is a different implementation of safe area view than the one built in core
2. the definitive source for this is https://www.npmjs.com/package/react-native-safe-area-view, we don't necessarily update on npm
3. if you want it, install it. if you don't, then don't, basically. you can read the readme to decide if it's something that you want to use: https://github.com/react-native-community/react-native-safe-area-view#react-native-safe-area-view

**Comment by schumannd** [comment]
@brentvatne can you elaborate on 2. a bit more? It does not answer my question about where I can check which versions contain which commits. Is that even possible?

**Comment by ripzery** [comment]
@brentvatne Please do a `Release` so we can help pointing out which commit is causing the bug in the given version. Otherwise, it's hard to know exactly where the changes start or end.🙇

**Comment by brentvatne** [comment]
@schumannd - sorry i meant to say we don't necessarily update releases tab on github

@ripzery - i did a release 11 days ago when i posted above, see version 1.1.1 (lots of 1s there, neat)

**Comment by schumannd** [comment]
@brentvatne Is there some other way to find out which commits are part of which release? I mean you must internally have some documentation of that. And I think it is very important information. Is there any way you could make that information public? Maybe through tags or something similar?

**Comment by brentvatne** [comment]
@schumannd - every commit before this commit in history https://github.com/react-native-community/react-native-safe-area-view/commit/93aa5462c049f2f0ad45fcb9fe22515e3a17bd32
