### ISSUE TITLE
TaskQueue: Error with task: undefined is not an object (this.view.component.measureInWindow)

### ISSUE THREAD

**Issue by mkchetan25** [react-native-community/react-native-safe-area-view#112]
# Bug

App doesn't load and throws this error:
![image](https://user-images.githubusercontent.com/31512936/78316086-60e16480-757c-11ea-835a-ce4a39af95cb.png)

## Environment info
OS: Win 10
Node Js: 10.x
"react-native-safe-area-view": "1.0.0",
react: 16.3.0
react-native: 0.62.0
react-redux: 5.1.1

## Steps To Reproduce

- It is fresh new project
- npm run android
- javascript bundles good, but loads with error in android

**Comment by brentvatne** [comment]
a fix for react-native@0.62 is available in react-native-safe-area-view@1.1.0! thanks for the report!
