### ISSUE TITLE
White flash when using this library with Wix react-natie-navigation

### ISSUE THREAD

**Issue by nathantqn** [react-native-community/react-native-safe-area-view#115]
# Bug

I'm facing the problem described on the title using `SafeAreaProvider` from `react-native-safe-area-context` together with `react-native-navigation` from Wix. If I have the SafeAreaProvider outside of the registered screen so there will be a white flash flickering during navigation. 

I think it's related to this issue https://github.com/wix/react-native-navigation/issues/4250. Because the outer SafeAreaView in this lib is from react-native, not react-native-navigation.

Code snippets are provided latter section.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 48.30 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: 0.7.3

## Steps To Reproduce

1. Using the SafeAreaProvider together with Wix react-native-navigation
2. If I have the SafeAreaProvider outside of the registered screen so there will be white flash and flickering during navigation.
...

Describe what you expected to happen:

1. During the navigation, there should not be a white flash or flickering

## Reproducible sample code

The function to get rid of white flash during navigation

```js
 Navigation.push(SCREEN.testScreen, {
      component: {
        name: SCREEN.testScreen2,
        options: {
          animations: {
            push: {
              waitForRender: true,
            },
          },
        },
      },
    });
  };
```

My code to register screen:
```js
  Navigation.registerComponent(
    SCREEN.testScreen2,
    () => ProviderWrapper(TestScreen2),
    () => TestScreen2,
  );
```

My ProvderWrapper
```js
import React from 'react';
import {gestureHandlerRootHOC} from 'react-native-gesture-handler';
import {SafeAreaProvider} from 'react-native-safe-area-context';

const ProviderWrapper = (Component: any) => {
  return (props: any) => (
    <SafeAreaProvider>
      <Component {...props} />
    </SafeAreaProvider>
  );
};

export default gestureHandlerRootHOC(ProviderWrapper);

```

If I remove the SafeAreaProvider, then the waitForRender works fine and there is no white flash or flickering.

**Comment by brentvatne** [comment]
this library is deprecated, use react-native-safe-area-context instead :)
