### ISSUE TITLE
I cannot install new Packages - EISGIT Error

### ISSUE THREAD

**Issue by yesIamFaded** [react-native-community/react-native-safe-area-view#121]
I have the EISGIT ERROR wich doesnt let me install anything inside my project.

I tried few commands like` rm -rf node_modules/@react-navigation/native/node_modules/react-native-safe-area-view/.git`  (and other rm commands but NONE works) but there is no such thing as -rf on windows.

Also tried removing the package manually from nodemodules didnt help.

How do I fixx this issue for windows10? Ty

**Comment by brentvatne** [comment]
new versions of react-native-safe-area-view don't have this issue and neither do new versions of @react-navigation/native :) use the latest versions please
