### ISSUE TITLE
Import variables got interchanged in the documentation.

### ISSUE THREAD

**Issue by sourabhbagrecha** [react-native-community/react-native-safe-area-view#123]
# Bug report

## Summary

check out the usage section at: https://www.npmjs.com/package/react-native-safe-area-view#usage
import variables should be in the following format:
```
import { SafeAreaProvider } from 'react-native-safe-area-view';
&
import { SafeAreaView } from 'react-native-safe-area-context';
```

currently, they are in the following format:
```
import { SafeAreaProvider } from 'react-native-safe-area-context';
&
import SafeAreaView from 'react-native-safe-area-view';
```

## Environment info

Please note: I am using expo

Library version: 
```
    "react-native-safe-area-context": "0.7.3"
    "react-native-safe-area-view": "^1.1.1"
```

## Steps to reproduce

1. In the documentation, it is mentioned that:
![image](https://user-images.githubusercontent.com/27056663/81811933-07892f80-9543-11ea-8757-f5be14f0fc88.png)
Fig.: https://www.npmjs.com/package/react-native-safe-area-view#usage

Describe what you expected to happen:
It should be in the following format:
![image](https://user-images.githubusercontent.com/27056663/81811657-9cd7f400-9542-11ea-92e9-6101436d243b.png)
![image](https://user-images.githubusercontent.com/27056663/81811751-c55fee00-9542-11ea-8d65-ebd4ad0f0a47.png)

**Comment by brentvatne** [comment]
thank you! fixed the readme
