### ISSUE TITLE
Update example of usage

### ISSUE THREAD

**Issue by RafaelFeiten** [react-native-community/react-native-safe-area-view#124]
Please update your example of usage, because you are exporting by DEFAULT the SafeAreaView, and causing conflicts when we usage.

**Today example:** import {SafeAreaView} from 'react-native-safe-area-view';
**Correct example:** import SafeAreaView from 'react-native-safe-area-view';

_Thanks a lot._

**Comment by vmarimuthu** [comment]
> Please update your example of usage, because you are exporting by DEFAULT the SafeAreaView, and causing conflicts when we usage.
> 
> **Today example:** import {SafeAreaView} from 'react-native-safe-area-view';
> **Correct example:** import SafeAreaView from 'react-native-safe-area-view';
> 
> _Thanks a lot._

You saved my day .. almost 1 hr waste ..

**Comment by nelsonprsousa** [comment]
Hey guys,

Do not use this library anymore. Use https://github.com/th3rdwave/react-native-safe-area-context instead. This one will be deprecated soon.

**Comment by lucasriondel** [comment]
@nelsonprsousa how do you know that ? it doesn't seem written anywhere

**Comment by nelsonprsousa** [comment]
> @nelsonprsousa how do you know that ? it doesn't seem written anywhere

Check [this one](https://github.com/react-navigation/react-native-safe-area-view/issues/98#issuecomment-633791884), for example.

**Comment by lucasriondel** [comment]
@nelsonprsousa thanks man !

**Comment by sonnd08** [comment]
@RafaelFeiten Thanks

**Comment by brentvatne** [comment]
this library is deprecated, use react-native-safe-area-context instead :)
