### ISSUE TITLE
Conflict with react-navigation and headerMode: 'none'

### ISSUE THREAD

**Issue by lucasfernandes** [react-native-community/react-native-safe-area-view#13]
Hi, I'm experiencing a weird behavior using safeAreaView and react-navigation.
Without safe area, when my StackNavigator is headerMode: 'none', everything goes fine, but when I use safeAreaView, the StackNavigator doesn't  works perfectly and don't hide the header completely, I know that probably is not a react-safe-area-view problem, but... maybe you guys can help with some tip.

Thats the illustration:
![simulator screen shot - iphone x - 2018-01-22 at 00 27 26](https://user-images.githubusercontent.com/29531/35202681-2e297e9a-ff0b-11e7-9fce-fdc881a9c381.png)

**Comment by jqn** [comment]
depending on what version of react-navigation you are on this component is already included and you don't need to import the standalone component from here

**Comment by lucasfernandes** [comment]
sorry, I thought the problem was with safeArea, but in fact was in the react-navigation and I solve in this way:

const Routes = StackNavigator({
  Identify: { screen: IdentifyRoutes },
}, {
  headerMode: 'none',
  cardStyle: { shadowColor: 'transparent' },
});

I'm closing this issue.
Thanks.
