### ISSUE TITLE
Remove curlies on import { SafeAreaView }

### ISSUE THREAD

**Issue by MarkChanner** [react-native-community/react-native-safe-area-view#132]
There shouldn't be curly braces around `import { SafeAreaView } from 'react-native-safe-area-view';`

**Comment by MarkChanner** [comment]
Update: I see a PR has been submitted which addresses this issue. It just needs merging:
https://github.com/react-navigation/react-native-safe-area-view/pull/129

**Comment by brentvatne** [comment]
this library is deprecated, use react-native-safe-area-context instead :)
