### ISSUE TITLE
Error null is not object (evaluating 'percent.includes') After migrating from rn 0.60 to rn 0.63.2 on ios only

### ISSUE THREAD

**Issue by khalilTN** [react-native-community/react-native-safe-area-view#133]
After migrating from rn 0.60 to rn 0.63.2, i got this error on ios, i'm not sure of its location, i can't find the code which caused it even with ctrl+f in the whole project
`null is not object (evaluating 'percent.includes')`
![Simulator Screen Shot - iPhone 11 - 2020-08-17 at 14 46 58](https://user-images.githubusercontent.com/9549132/90404060-c18bbc80-e099-11ea-9fb2-dd8ed6fdfb58.png)
![Simulator Screen Shot - iPhone 11 - 2020-08-17 at 14 44 00](https://user-images.githubusercontent.com/9549132/90404186-f0a22e00-e099-11ea-97a6-b9858944db03.png)

**Comment by bllyanos** [comment]
same error here..

**Comment by brentvatne** [comment]
this library is deprecated, use react-native-safe-area-context instead :)
