### ISSUE TITLE
Not working correctly on iPhone 12 Series phones

### ISSUE THREAD

**Issue by marcinkornek** [react-native-community/react-native-safe-area-view#136]
**Current Behavior**
SafeAreaView is not working correctly on iPhone 12 Series phones
I created simple app to reproduce it
```
import React from 'react';
import { Text, View } from 'react-native';
import SafeAreaView from 'react-native-safe-area-view'

const App = () => (
  <SafeAreaView style={{ flex: 1, backgroundColor: 'red' }}>
    <View style={{ flex: 1, backgroundColor: 'yellow' }}>
      <Text>Home Screen</Text>
    </View>
  </SafeAreaView>
)

export default App
```
![image](https://user-images.githubusercontent.com/7931279/96857177-faac2880-145e-11eb-8f47-55f5d644d005.png)

but I realized that it's even not working with example from README:
![image](https://user-images.githubusercontent.com/7931279/96857261-11eb1600-145f-11eb-8343-2f98d277c2c8.png)

I even tried to add `forceInset` `bottom: 'always'` but without any change
```
  <SafeAreaView 
    style={{ flex: 1, backgroundColor: 'red' }}
    forceInset={{
      bottom: 'always'
    }}
  >
```

and with `forceInset` `vertical: 'always'` it changes it a little bit but still not correct
![image](https://user-images.githubusercontent.com/7931279/96857751-a2c1f180-145f-11eb-89a0-f32d45b839ae.png)

**My Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 |
| react-native-safe-area-context | ^3.1.8 |
react-native-safe-area-view | ^0.14.9 |
| react-native      |      0.63.3       |
| node      |    v13.8.0                 |
| yarn     |  1.22.0             |

**Comment by marcinkornek** [comment]
I checked newest `react-native-safe-area-view` 2.0.0 version and it's working fine so I'm closing the issue

**Comment by comvenger-brandon** [comment]
2.0.0 does not seem to be properly released on npm?

**Comment by ethanyuwang** [comment]
also having this problem

**Comment by xutm** [comment]
Why don't I have 0.14.9 versions?

```shell
~/tomorrow/asgard(feat-rush*) » npm i --registery=https://registry.npm.taobao.org react-native-safe-area-view@0.14.9           tianmingxu@MacBook-Pro-5
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-native-safe-area-view@0.14.9
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tianmingxu/.npm/_logs/2020-10-29T09_32_58_322Z-debug.log
------------------------------------------------------------
~/tomorrow/asgard(feat-rush*) » npm i --registery=https://registry.npm.taobao.org react-native-safe-area-view                  tianmingxu@MacBook-Pro-5
npm WARN @xhs/asgard@3.40.0-1 requires a peer of @xhs/rex-style@^3.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @xhs/asgard@3.40.0-1 requires a peer of @xhs/protobuf-apm-tracker@^2.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN @react-native-community/cli@1.6.0-fork9 requires a peer of react-native@^0.59.0 but none is installed. You must install peer dependencies yourself.
npm WARN @xhs/react-native-sentry@0.42.1 requires a peer of react-native@>=0.56.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-jest@21.2.0 requires a peer of babel-core@^6.0.0 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-transitions@1.0.12 requires a peer of react-navigation@* but none is installed. You must install peer dependencies yourself.
npm WARN react-test-renderer@16.13.1 requires a peer of react@^16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN @xhs/asgard@3.40.0-1 No license field.

+ react-native-safe-area-view@0.13.3
updated 1 package in 6.366s
```

**Comment by Farhan7786** [comment]
Also having the same problem here. on iPhone 12 series.

**Comment by Abhishek-Sankey** [comment]
I'm still facing issues with the header...

**Comment by Abhishek-Sankey** [comment]
I'm still facing some issues with the header...
I've updated the package react-native-safe-area-view and added into the package.json as
 "resolutions": {
    "react-native-safe-area-view": "^2.0.0"
  },
Plz let me know if I'm doing anything wrong
Thanks
