### ISSUE TITLE
Not working on iPhone 12

### ISSUE THREAD

**Issue by Abhishek-Sankey** [react-native-community/react-native-safe-area-view#138]
SafeAreaView is not working for iPhone 12 series phone. It's working correctly for iPhone 11 and the old ones.
I'm reopening the issue [here](https://github.com/react-navigation/react-native-safe-area-view/issues/136). I've tried to update the library but no luck.
Screenshot: 
![Screenshot 1942-08-12 at 4 30 24 PM](https://user-images.githubusercontent.com/53463010/97977728-a60b9480-1df2-11eb-87da-2d24ecfd6364.png)
Dependencies:

1. react-native-safe-area: 0.5.1
2. react-navigation: 4.4.1
3. react-native: 0.63.3

I've tried to use the `react-native-safe-area-context` for insets values but still, the issue is present.
Thanks!

**Comment by vitalyrotari** [comment]
same problem with react-navigation v4

**Comment by sebastianor** [comment]
Same here for react-navigation v4 and: 
    "react-native-safe-area-context": "^1.0.2",
    "react-native-safe-area-view": "^2.0.0",

**Comment by Lino-saur** [comment]
index.js didn't provide iPhone12 series support.

```
const X_WIDTH = 375;
const X_HEIGHT = 812;
const XSMAX_WIDTH = 414;
const XSMAX_HEIGHT = 896;
const PAD_WIDTH = 768;
const PAD_HEIGHT = 1024;

const IPHONE12_H = 844;
const IPHONE12_Max = 926;
const IPHONE12_Mini = 780;


const { height: D_HEIGHT, width: D_WIDTH } = Dimensions.get('window');

const { PlatformConstants = {} } = NativeModules;
const { minor = 0 } = PlatformConstants.reactNativeVersion || {};

const isIPhoneX = (() => {
  if (Platform.OS === 'web') return false;

  return (
    Platform.OS === 'ios' &&
    ((D_HEIGHT === X_HEIGHT && D_WIDTH === X_WIDTH) ||
      (D_HEIGHT === X_WIDTH && D_WIDTH === X_HEIGHT)) ||
    ((D_HEIGHT === XSMAX_HEIGHT && D_WIDTH === XSMAX_WIDTH) ||
          (D_HEIGHT === XSMAX_WIDTH && D_WIDTH === XSMAX_HEIGHT)) ||
      (D_HEIGHT === IPHONE12_H) || (D_HEIGHT === IPHONE12_Max) || (D_HEIGHT === IPHONE12_Mini)
  );
})();
```

Add some iPhone12 related adjustments to index.js will solve the issue.

using: 
react-native-safe-area-view": "0.11.0

**Comment by Abhishek-Sankey** [comment]
![Screenshot 1942-08-15 at 6 51 40 PM](https://user-images.githubusercontent.com/53463010/98370819-30593000-2061-11eb-9a8f-c5bee1c808b4.png)
I've solved the issue by updating these 3 libraries.
Closing this issue now.
Let me know if anyone faces any issue.

**Comment by sebastianor** [comment]
@Abhishek-Sankey are You using react-navigation v5 or v4 ?

**Comment by Abhishek-Sankey** [comment]
> @Abhishek-Sankey are You using react-navigation v5 or v4 ?

it's v4

**Comment by sebastianor** [comment]
Okay, I got it. I had custom height of the header that's why it didn't work after update libraries. Thank You for answer 😄

**Comment by mrarronz** [comment]
> const IPHONE12_H = 844;
> const IPHONE12_Max = 926;
> const IPHONE12_Mini = 780;

Hi @LoKiLyn , your solution looks good to fix the header inset issue on iPhone 12. 

Do you have any solutions to fix the bottom bar issue [Bottom bar too low](https://github.com/react-navigation/react-navigation/issues/8972)??

 I know this is another problem and should raise this question under that issue, but I'm using old version of `react-navigation` and `react-native-safe-area-view`, as you know that `react-navigation` has so many dependencies which also includes `react-native-safe-area-view`, it's a big risk to upgrade so many dependencies at once and it takes a big effort to maintain my project. So I want to only make a minor change like you did on the current old version library.

The bottom tabs are very low on the iPhone 12, that may need make some code change on `react-navigation-tabs`, I'm not sure if there is a certain way to fix this, could you please help? I thought you may have some good suggestions like what you did on `react-native-safe-area-view`(e.g. add support to iPhone 12).

I'm using libraries:
```
react-navigation: 2.0.1
react-native-safe-area-view: 0.14.6   (installed along with react-navigation, I changed the original version to 0.14.6)
react-navigation-tabs: 0.2.0 (installed along with react-navigation)
```

**Comment by luatnd** [comment]
Any solution on react-navigation v3?
I think I would follow @LoKiLyn 's solution
