### ISSUE TITLE
react-native-web does not provide DeviceInfo, and this package depends on it being there.

### ISSUE THREAD

**Issue by raarts** [react-native-community/react-native-safe-area-view#16]
react-native-web aliases `import ... from 'react-native'` into `import ... from 'react-native-web'`. 

The maintainer of react-native-web does not support undocumented react native components, and DeviceInfo is one of them. So if you want to use this package under react-native-web, you'll get errors. 

I want to fix this, so I'm only creating this issue, so I can provide a PR against it.

**Comment by davepack** [comment]
Fixed in https://github.com/react-community/react-native-safe-area-view/pull/18 :-)
