### ISSUE TITLE
_reactNative.Dimensions.addEventListener is not a function

### ISSUE THREAD

**Issue by hyperh** [react-native-community/react-native-safe-area-view#23]
I'm on`react-native` 0.34.1 and trying to use `react-native-safe-area-view` 0.7.0 for iPhone X. Getting the following error

`
_reactNative.Dimensions.addEventListener is not a function (In '_reactNative.Dimensions.addEventListener('change', this.handleOrientationChange)', '_reactNative.Dimensions.addEventListener' is undefined)
`

**Comment by spotsadmin** [comment]
@hyperh did you find any solution? I see the same issue on RN 0.42 as well

**Comment by hyperh** [comment]
@spotsadmin Don't recall what I did for this sorry.

**Comment by spotsadmin** [comment]
I saw this PR fixes this issue - https://github.com/react-community/react-native-safe-area-view/pull/19
