### ISSUE TITLE
first render flickers if overriding the inset

### ISSUE THREAD

**Issue by mmerickel** [react-native-community/react-native-safe-area-view#26]
Currently `touchesTop` defaults to `true`. If a component is not actually touching the top there is a rendering artifact where the component is rendered with padding until a measurement can be done in `componentDidMount` + `InteractionManager.runAfterInteractions` + `_onLayout` which then discovers the component is not touching the top and adjusts to the correct position after the `setState` call from `_onLayout`. This effect is highly noticeable though and is not present in react-native's native `SafeAreaView` impl.

I do not see a way to fix this because of the chicken-and-egg issue of needing to render the component to determine if it's touching but maybe it could be done with an invisible view or something to avoid such a bad content shift.

**Comment by davepack** [comment]
Add `forceInset={{ top: 'always' }}`. SafeAreaView has no idea where it is until it measures, which in JS is delayed by one frame after render, hence the jump. 

I don't think there should be any case where the dev doesn't know if and when the view will be touching an edge and has much more efficient means to dynamically set the inset with `forceInset`.

**Comment by mmerickel** [comment]
The issue here is that I want `forceInset={{ top: 'never' }}` but there is no way to make that happen afaict. Perhaps `touchesTop`, `touchesBottom` etc should be initialized based on the prop instead of hardcoded to `true`.

**Comment by davepack** [comment]
You can do that, double check the readme:

>forceInset takes an object with the keys top | bottom | left | right | vertical | horizontal and the values 'always' | 'never'

Honestly I'm not experienced at writing documentation, so it may just need to be rewritten to be more clear.

**Comment by mmerickel** [comment]
I might not be explaining myself well, I'm aware of the options, but going back to my original issue ... if I set `forceInset={{top: 'never'}}` there is a flicker for me where the content is shifted down initially (from the default of `state.touchesTop === true`) and then once it does its thing it shifts the content up, removing the padding so that it is correct.

**Comment by davepack** [comment]
Yeah, sorry, it wasn't clear to me you were already setting the top inset to 'never'. It shouldn't flicker, `forceInset` was added specifically to prevent the flicker. If forceInset is set, the inset is set to 0 in `_getSafeAreaStyle` ([here](https://github.com/react-community/react-native-safe-area-view/blob/master/index.js#L214)).

Can you create a [snack](https://snack.expo.io/) or paste some code that reproduces the problem?

**Comment by mmerickel** [comment]
I was able to repro this easily earlier today and now on my other box I cannot so I'm going to close this for now and when/if I hit it again I will reopen. Thanks :-)
