### ISSUE TITLE
Warning: Can't call setState (or forceUpdate) on an unmounted component..

### ISSUE THREAD

**Issue by ajayvikas** [react-native-community/react-native-safe-area-view#28]
This is related to the issue  react-navigation/react-navigation#3992 raised at React Navigation repository, which I tracked down to SafeView Component in this repository. The problem is happening when the measureInWindow is being called at time the component has already dismounted. To fix this all we need to check the existence of view before proceeding further. So please add the following code at line number 153.
``
      if (!this.view) return;
``

**Comment by lijunle** [comment]
Same here. Hope that somebody could apply the @ppn2 's fix into the code.

**Comment by Ashoat** [comment]
Putting up PRs is probably easier than you guys think :)

I'll do it.

**Comment by giacomocerquone** [comment]
jeez this was driving me nuts guys 💀
