### ISSUE TITLE
Should react and react-native be peerDependencies?

### ISSUE THREAD

**Issue by keith-kurak** [react-native-community/react-native-safe-area-view#3]
When I install this as an npm package in my project, I get "Ambiguous resolution: module [path in my project] tries to require 'react-native', but there are several files providing this module. You can delete or fix them.

I think if react and react-native were listed as peerDependencies in your package.json, it would use the react/ react-native included in my project and it would work.

**Comment by keith-kurak** [comment]
I see there's a pull request for this already: https://github.com/react-community/react-native-safe-area-view/pull/1

**Comment by davepack** [comment]
yes, closing this, just merged that PR. Thanks!
