### ISSUE TITLE
Doesn't work in landscape?

### ISSUE THREAD

**Issue by FezVrasta** [react-native-community/react-native-safe-area-view#4]
It looks like this component doesn't add any padding in landscape, but this is going to allow elements to be rendered below the status bar.

Am I missing something maybe?

**Comment by davepack** [comment]
Sometimes the measurement is inaccurate from onLayout. If you know a View is always going to touch an edge of the screen, but SafeAreaView is not adding padding automatically, use `forceInset={{ [edge]: 'always' }}` to force the correct padding on iPhoneX. It will automatically adjust according to orientation.

**Comment by davepack** [comment]
Unless I misunderstood your question. Padding gets added to top and bottom edges when in portrait and left and right edges in landscape.

**Comment by FezVrasta** [comment]
I was thinking that this component would have added padding also for the status bar

**Comment by davepack** [comment]
It does add padding for the status bar. Can you share a screenshot and code that shows the problem you’re having?

**Comment by alizain-wal** [comment]
It doesn't add padding on iOS 10 and earlier.

**Comment by FezVrasta** [comment]
I just add the view with inside some text and I reproduce the problem.

**Comment by davepack** [comment]
What device is this on? Can you share a screen shot?

**Comment by cguyer** [comment]
I believe this is what he is talking about with the use of react navigation:
iPhone 5S - ios 11.3
Portrait
![img_0009](https://user-images.githubusercontent.com/516385/39135609-53d99e6c-46e7-11e8-8cf7-f0fd6b831a6e.png)
Landscape
![img_0010](https://user-images.githubusercontent.com/516385/39135620-59fa4454-46e7-11e8-88b2-7e82d170b32a.png)

I've been actually debugging to see if it is just a missed setting, bad code or an actual bug. In portrait there is automatic padding at top for older iphone with safeareaview but when you rotate to landscape the status bar is hidden but if you swipe down to show status bar it then displays it and the bar remains there after closing, overlapping the header (see time/battery icons in landscape image)

It may be related to https://github.com/facebook/react-native/issues/18005 as the iOS status bar gets hidden by default. So if on load the iOS status is not there and no padding is added but then you swipe down for notifications, the bar is then displayed and does not go away resulting in overlap.

**Comment by brentvatne** [comment]
this should be resolved in version 1.0 which was released today, thanks for reporting!
