### ISSUE TITLE
Require cycle in withSafeArea.js line 4

### ISSUE THREAD

**Issue by Kennytian** [react-native-community/react-native-safe-area-view#40]
![](https://wx1.sinaimg.cn/mw690/77c29b23ly1fuo9dipdecj20u411qk3n.jpg)

Require cycle: node_modules/react-native-safe-area-view/index.js -> node_modules/react-native-safe-area-view/withSafeArea.js -> node_modules/react-native-safe-area-view/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

**Comment by rogueturnip** [comment]
I'm seeing this issue also using react-native 0.57.0-rc.3.  Did you find why this was occurring?

**Comment by gurglet** [comment]
It's because index.js imports withSafeArea.js, which in turn imports index.js, leading to an import cycle.

You can suppress the warning until it's fixed with:

```js
import { YellowBox } from 'react-native';
YellowBox.ignoreWarnings(['Require cycle:']);
```

**Comment by Kennytian** [comment]
@gurglet  Thanks for your response.  but I don't think ignore warnings it is a good way.

I saw you post a pull request, really hope can merge it asap.

**Comment by Kennytian** [comment]
#41 close

**Comment by kuriel-dev** [comment]
Thanks @gurglet , i can ignore visual warnings with 
`YellowBox.ignoreWarnings(['']);`

they are useless since they are printed in console, thank you bro.

**Comment by Pratap22** [comment]
@ningacoding  Where do u placed the code??

**Comment by Pratap22** [comment]
@gurglet  Where to place those codes?

**Comment by kuriel-dev** [comment]
@Pratap22 you can add that code in almost any place where your app is running, i placed the code in the App.js of the app. (the first js that runs) so it's globally added.
