### ISSUE TITLE
Version 0.11.0 missing from the repo

### ISSUE THREAD

**Issue by stigi** [react-native-community/react-native-safe-area-view#49]
Hi,

It [looks like 0.11.0](https://www.npmjs.com/package/react-native-safe-area-view) has been released (including the fix for iPhone XS Max et al) but the repo doesn't reflect the version bump. 

Maybe a few commits haven't been pushed.

Thanks for checking

**Comment by brentvatne** [comment]
not sure what happened here but closing as it's now out of date
