### ISSUE TITLE
run error: two 'react-native' modules after installing

### ISSUE THREAD

**Issue by Versus2017** [react-native-community/react-native-safe-area-view#5]
#### Here is what I do:
- npm install react-native-safe-area-view --save
- run iPhone X simulator
- then error occurred

#### Here is the error:
`error: bundling failed: ambiguous resolution: module /Users/dongfanggouwu-xiong/WebstormProjects/untitled/index.js tries to require react-native, but there are several files providing this module. You can delete or fix them:`

- `/Users/dongfanggouwu-xiong/WebstormProjects/untitled/node_modules/react-native-safe-area-view/node_modules/react-native/package.json`

- `/Users/dongfanggouwu-xiong/WebstormProjects/untitled/node_modules/react-native/package.json
 `

**Comment by davepack** [comment]
what version of react-native-safe-area-view do you have installed? The latest should solve this issue

**Comment by Versus2017** [comment]
My react-native version is 0.48, and I don't want to upgrade to the latest version. I've solved this issue by using the new version of react-navigation, cause it contains safe-area-view. thanks

**Comment by davepack** [comment]
glad it worked out
