### ISSUE TITLE
Unable to resolve “./withSafeArea” from “node_modules\react-native-safe-area-view\index.js”

### ISSUE THREAD

**Issue by panda0603** [react-native-community/react-native-safe-area-view#50]
I've just updated my React native version to 0.57 from 0.55.

I'm getting bunch of errors starting from Barbel, fixing errors one by one.

Now I'm encountering

"Unable to resolve "./withSafeArea" from "node_modules\react-native-safe-area-view\index.js"

Error, and that's all information the console gives. I tried googling it, seems like I'm the first one encountering this error. What is the error here?

So far I've tried:

delete node_modules folder and do npm install again.

npm install react-native-safe-area-view.

Both no luck :(

**Comment by phalera** [comment]
You can delete "export {withSafeArea}" in node_modules\react-native-safe-area-view\index.js , and add export before "const withSafeArea"

**Comment by skrywus** [comment]
Have the same as @panda0603. Any updates?

**Comment by kas** [comment]
Experiencing the same issue, created #70 .

**Comment by uhbsksingh** [comment]
yarn add react-native-safe-area-view react-native-safe-area-context
