### ISSUE TITLE
iPad Pro 11-Inch (2018) Not Supported

### ISSUE THREAD

**Issue by dustinbahr** [react-native-community/react-native-safe-area-view#54]
The new iPad Pro 11-Inch has rounded corners and no physical home button similar to the new iPhones.

When using this safe area view, the status bar is accounted for as expected, but the bottom area with the virtual home button is NOT.

**Comment by cesargdm** [comment]
PR https://github.com/react-native-community/react-native-safe-area-view/pull/55

**Comment by cesargdm** [comment]
72daea8bcf0bfb29c66383fe9e91325be19ee2cb

**Comment by Phecda** [comment]
iPad Pro 12.9-inch type has 3 generations with same screen dimensions, and only 3rd generation need safe area insets. So it seems that we cannot tell whether it is a 3rd generation only by screen dimensions. 🤔

**Comment by Liqiankun** [comment]
@cesargdm It works!

**Comment by Sushant-Sardeshpande** [comment]
Doesn't seem to be working for me.

**Comment by brentvatne** [comment]
this should be resolved in version 1.0 which was released today, thanks for reporting!
