### ISSUE TITLE
How to remove Shadow

### ISSUE THREAD

**Issue by deepak28** [react-native-community/react-native-safe-area-view#60]
Thanks for this great useful library,

I need to remove the shadow of `SafeAreaView`.
![screenshot 2019-01-30 at 2 50 43 pm](https://user-images.githubusercontent.com/4962749/52104950-afab0b80-2612-11e9-8ce3-e98ba247a052.png)

**Comment by chris-feist** [comment]
I'm experiencing the same issue. I tried playing with `zIndex` for all the views too and no luck

**Comment by MayeuldP** [comment]
Same over here, did you managed to find something ?

**Comment by cbjs** [comment]
same.

**Comment by gianpaj** [comment]
This is related to `react-navigation`. You remove it like this:
https://stackoverflow.com/questions/48361898/how-to-remove-internal-shadow-of-react-native-stacknavigator-when-using-safearea

```js
const Routes = StackNavigator({
  // ...
}, {
  headerMode: 'none',
  cardStyle: { shadowColor: 'transparent' }, // < == this
});
```

**Comment by chris-feist** [comment]
@gianpaj solution didn't work. However, I played around with stuff more and determined that reducing the `shadowRadius` of my Toolbar removed the shadow between my toolbar and the status bar. It appears that the child of the `SafeAreaView` in the original screenshot has a shadow applied, so likely that needs to be modified (if needed at all). Here is the shadow definition for my Toolbar:
```
    shadowColor: 'black',
    shadowOpacity: 0.26,
    shadowRadius: 0.3 * elevation, // elevation = 4
    shadowOffset: {
      width: 0,
      height: 0.5 * elevation,
    },
```

**Comment by brentvatne** [comment]
don't wrap your entire app in a safe area view, you need to use it selectively. https://reactnavigation.org/docs/en/handling-iphonex.html explains

**Comment by cseelus** [comment]
Current docs for using it with React Navigation: https://reactnavigation.org/docs/handling-safe-area/

**Comment by cglacet** [comment]
The only way I found so far is this **ugly thing**: 

```
elevation: 601,
```

On my phone 601 is the first elevation for which it works, with 600 it produces strange things. I can imagine that this limit depend on context so if you use this even **uglier thing**, that should always work:

```
elevation: 10**10,
```

I wonder why they have such a weird API on android … Why did they chose to mix zIndex logic with shadow logic, that's so restrictive for users.
