### ISSUE TITLE
.git file made it's way into release on NPM

### ISSUE THREAD

**Issue by Andrewsh86** [react-native-community/react-native-safe-area-view#69]
"/path/to/my/project/node_modules/react-native-safe-area-view: Appears to be a git repo or submodule."

I'm getting this message whenever I try to run an NPM install. 

It looks like a .git file made it into the release on NPM and is causing this issue.

If I delete the file, it shows back up on subsequent npm installs.

**Comment by bluefirepatrick** [comment]
I can confirm this issue.  Removing the .git directory fixes it.

**Comment by Andrewsh86** [comment]
> Removing the .git directory fixes it.

Does the .git director show back up for you on subsequent npm installs?

**Comment by yogeshchoudhary147** [comment]
I think it has started happening with 0.13.2. Never saw this since yesterday.

**Comment by travisraghib** [comment]
Can we get this sorted out asap?

**Comment by dimgrav** [comment]
Please take care of this.

**Comment by pniedzwiedzinski** [comment]
+1

**Comment by dkocich** [comment]
same issue here - I am trying to add typescript into my Expo project (following  https://docs.expo.io/versions/latest/guides/typescript/) but I see this:

```
david@HPdk:~/it/XYZ$ npm install --save-dev typescript@^3.3.0 @types/expo@^32.0.0 @types/react-native@^0.57.0
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN enoent ENOENT: no such file or directory, open '/home/david/it/XYZ/node_modules/metro/node_modules/sane/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/david/it/XYZ/node_modules/metro-core/node_modules/sane/package.json'

npm ERR! path /home/david/it/XYZ/node_modules/react-native-safe-area-view
npm ERR! code EISGIT
npm ERR! git /home/david/it/XYZ/node_modules/react-native-safe-area-view: Appears to be a git repo or submodule.
npm ERR! git     /home/david/it/XYZ/node_modules/react-native-safe-area-view
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2019-05-12T18_17_46_775Z-debug.log
```

`rm -rf .git` inside `/node_modules/react-native-safe-area-view$` helped to solve this and installation passes...

similar approach was mentioned here https://github.com/APSL/react-native-version-number/issues/13

**Comment by jgfoster** [comment]
In our experience, after removing .git subsequent installs did not bring it back. So, the workaround is not too bad once you recognize the problem.

**Comment by Andrewsh86** [comment]
I was having it show back up after removal both during an npm install and npm audit.

Not sure why it would be different.

In any case, it should be fixed as soon as possible.

**Comment by fluiddot** [comment]
Any update on this?
_(I came to this repo because I updated `react-navigation` so this is probably affecting a lot of people)_

The workaround of removing the `.git` folder works but it's pretty nasty to have to do it for preventing this error.

By the way this is the command I used for fixing it:
`rm -rf node_modules/@react-navigation/native/node_modules/react-native-safe-area-view/.git`

**Comment by tdipadova3rd** [comment]
Please fix, this breaks our CI tests as well.

**Comment by stevenbdf** [comment]
Same issue node_modules\react-native-safe-area-view: Appears to be a git repo or submodule.

**Comment by adam-buckley** [comment]
It's frustrating when I'm trying to upgrade react and for debugging purposes am constantly removing node_modules and reinstalling, then getting this error, so I made a little script that might help someone else (using linux - should work on mac):

Put this in your project folder, call it whatever (mine was "fix-safe-view.sh")
```sh
#!/bin/bash

rm -rf ./node_modules/@react-navigation/native/node_modules/react-native-safe-area-view/.git
rm -rf ./node_modules/react-native-safe-area-view/.git
```
Then run `chmod +x ./fix-safe-view.sh`, then invoke it like `./fix-safe-view.sh && npm install ...`

**Comment by SirCameron** [comment]
... seriously.

**Comment by djedou** [comment]
test

**Comment by MaheshNandam** [comment]
Thanks, @adam-buckley.

It's working for me.

**Comment by AyushG3112** [comment]
Yarn works fine though

**Comment by caclowers** [comment]
What's the status? Is this even being looked at?

**Comment by movaldivia** [comment]
Isn't `rm -rf .git` a bad practice?

**Comment by pcowgill** [comment]
@fluiddot Think it's worth creating an issue on the [`react-navigation`](https://github.com/react-navigation/react-navigation) repo too, since I imagine many people ran into this issue because this is a dep of that package?

**Comment by adam-buckley** [comment]
@movaldivia I'm not 100% sure if it is or isn't in the context of NPM, but it's obvious it shouldn't be there since this issue breaks interactions with NPM. I'm guessing the standard practice is to not publish an NPM package with the .git folder included.

**Comment by jdnichollsc** [comment]
same issue here using expo

**Comment by yyhappynice** [comment]
same issue

**Comment by usmankhan495** [comment]
This work for me.
- Removed the folder 'react-native-safe-area-view' manually
- Removed cache using npm start -- --reset-cache
- Run the command npm --save install react-native-gesture-handler

Source : https://stackoverflow.com/questions/56123618/error-when-installing-react-native-gesture-handler-with-npm

**Comment by pcowgill** [comment]
@brentvatne Would it be possible to publish another version to npm this week without the `.git` file? Thanks!!

**Comment by mariorodriguespt** [comment]
The proposed fixes with npm do no work for me, however installing packages with yarn seems to "fix" the problem.

**Comment by Rileyp33** [comment]
This is still an issue that’s a big blocker for development as all npm installs result in this error and require deleting the directory from node_modules. Seems like a quick fix to remove the offending file, please update!

**Comment by braianj** [comment]
Any solution for this I get same error and can't install any package

**Comment by nikokent** [comment]
> In our experience, after removing .git subsequent installs did not bring it back. So, the workaround is not too bad once you recognize the problem.

This fixed it for me! I just started react native today so was semi discouraged to see a framework where no modules could be imported 😅

**Comment by brentvatne** [comment]
https://github.com/react-native-community/react-native-safe-area-view/commit/1f8d3897144fd6512e42c49a2be6f4a95c101515

**Comment by braianj** [comment]
> > In our experience, after removing .git subsequent installs did not bring it back. So, the workaround is not too bad once you recognize the problem.
> 
> This fixed it for me! I just started react native today so was semi discouraged to see a framework where no modules could be imported

I solve it using yarn instead of npm

**Comment by pcowgill** [comment]
@brentvatne Thanks for the fix!

For anyone watching this issue, after that fix https://github.com/react-native-community/react-native-safe-area-view/commit/1f8d3897144fd6512e42c49a2be6f4a95c101515, if you remove the package `react-native-safe-area-view` from `node_modules` one last time, future `npm install`s will work

**Comment by jdnichollsc** [comment]
@brentvatne thanks for your help! <3

**Comment by larkinds** [comment]
Hi there, removing npm react-native-safe-area-view and then npm installing is not working for me

**Comment by larkinds** [comment]
This fix is not working for me! Either with 0.14.2 or 0.14.3 - I'm getting the same error message as before.

**Comment by brentvatne** [comment]
what version of npm are you using @larkinds? also can you share a project that reproduces the issue?

i'd suggest using yarn instead of npm btw - https://yarnpkg.com/ - it's generally more reliable and faster in my experience

**Comment by pavjacko** [comment]
add this to your npm scripts:

```
"scripts": {
"fix": "rm -rf node_modules/react-native-safe-area-view/.git && rm -rf node_modules/@react-navigation/native/node_modules/react-native-safe-area-view/.git && rm -rf node_modules/react-navigation/node_modules/react-native-safe-area-view/.git"
}
```
and run `npm run fix` after initial failure

(there might be other deps affected)

this helps until properly fixed release propagates out (inc dependant libs like react navigation)

**Comment by yesIamFaded** [comment]
this does not work there is no operation called rm on windows!

**Comment by dkocich** [comment]
> this does not work there is no operation called rm on windows!

use https://www.npmjs.com/package/rimraf locally in your project instead

**Comment by yesIamFaded** [comment]
@dkocich how do I install rimraf if I cant npm install ?

**Comment by brentvatne** [comment]
this issue has been resolved for a very long time as far as i know. if you are still having an issue please share a https://stackoverflow.com/help/mcve that demonstrates it
