### ISSUE TITLE
npm ERR! code EISGIT, Appears to be a git repo or submodule

### ISSUE THREAD

**Issue by fredrik-jarnbrost** [react-native-community/react-native-safe-area-view#73]
I get this when I do `npm install`. I'm happy to provide more info if needed.

```npm ERR! path /Users/fredrikve/Stagecast/goteborgsvarvapp/node_modules/react-native-safe-area-view
npm ERR! code EISGIT
npm ERR! git /Users/fredrikve/Stagecast/goteborgsvarvapp/node_modules/react-native-safe-area-view: Appears to be a git repo or submodule.
npm ERR! git     /Users/fredrikve/Stagecast/goteborgsvarvapp/node_modules/react-native-safe-area-view
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

EDIT: this happens on a fresh `npm install`

**Comment by a379351939** [comment]
same as you

**Comment by Irislm** [comment]
Try it  `rm -rf node_modules/*/.git/`.   It works for me!

**Comment by jqn** [comment]
Thanks @Irislm I ran the command and it fixed the issue. I'm still wondering what caused the issue on the first place.

**Comment by fredrik-jarnbrost** [comment]
@Irislm Thanks for the work-around. I edited the issue to specify when this happens

**Comment by pcowgill** [comment]
@fredrik-jarnbrost @a379351939 @Irislm @jqn FYI it's fixed in this commit https://github.com/react-native-community/react-native-safe-area-view/commit/1f8d3897144fd6512e42c49a2be6f4a95c101515

See this comment in another issue https://github.com/react-native-community/react-native-safe-area-view/issues/69#issuecomment-493078618

**Comment by fredrik-jarnbrost** [comment]
Oh didn't find that issue when I searched, sorry. Thanks for the quick help!

Closing this, duplicate of https://github.com/react-native-community/react-native-safe-area-view/issues/69

**Comment by shahidx-iqbal** [comment]
> Thanks @Irislm I ran the command and it fixed the issue. I'm still wondering what caused the issue on the first place.

where to run??

**Comment by jqn** [comment]
@shadyo7 run it in the root of your project where the node_modules directory is located

**Comment by saeedhemmati** [comment]
Also me!

**Comment by drpiou** [comment]
it breaks my project

**Comment by laptran-sym** [comment]
> Try it `rm -rf node_modules/*/.git/`. It works for me!

Thanks it work for me

**Comment by LeRoyJulian** [comment]
If you have this problem with Homebrew :  rm -rf /usr/local/lib/node_modules/*/.git/ then update again.

**Comment by malikkurosaki** [comment]
> If you have this problem with Homebrew : rm -rf /usr/local/lib/node_modules/*/.git/ then update again.

good job , this worked for me

**Comment by shahidx-iqbal** [comment]
> @shadyo7 run it in the root of your project where the node_modules directory is located
i run it in root files but get this

'rm' is not recognized as an internal or external command,
operable program or batch file.
jqn

**Comment by malikkurosaki** [comment]
BEST PROMO LICENSI FEE PERIODE JULY-DECEMBER 2019
Dapatkan promo terbaik dari kami dengan membayar Licensi Tahunan. Cukup
Bayar 10 Bulan (Free 2 Bulan) + Dapatkan Special Gift Dari Kami (silahkan
dipilih salah satu😇).
Promo berakhir sampai akhir Desember 2019. Jadi, jangan sampai ketinggalan
promo special dari kami.
Untuk informasi lebih lanjut silahkan hubungi kami :
Contact : Tugek sri WA 0821-44-55-00-76 Telp (0361) 725 901
TUGEK SRI Admin Finance Email: probussystem@gmail.com CV. MITRA SOLUSI
MANDIRI Jl. Bedugul 17D, Pertokoan De'a Graha Sidakarya, Denpasar, Bali,
80224 www.probussystem.com No problem, only solutio

Pada tanggal Sen, 8 Jul 2019 pukul 14.03 shadyo7 <notifications@github.com>
menulis:

**Comment by Phuonglv123** [comment]
> > @shadyo7 run it in the root of your project where the node_modules directory is located
> > i run it in root files but get this
> 
> 'rm' is not recognized as an internal or external command,
> operable program or batch file.
> jqn

delete node_modules and then npm install

**Comment by graniczny** [comment]
Hi!
I've got the same problem with @tensorflow/tfjs package. 
When I install it locally everything works, problem appears when I deploy it on CircleCi -> Google Kubernetess.

I get this err:
npm ERR! path /root/repo/node_modules/@tensorflow/tfjs-converter
npm ERR! code EISGIT
npm ERR! git /root/repo/node_modules/@tensorflow/tfjs-converter: Appears to be a git repo or submodule.
npm ERR! git     /root/repo/node_modules/@tensorflow/tfjs-converter
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

any ideas?

**Comment by cnebs** [comment]
> Hi!
> I've got the same problem with @tensorflow/tfjs package.
> When I install it locally everything works, problem appears when I deploy it on CircleCi -> Google Kubernetess.
> 
> I get this err:
> npm ERR! path /root/repo/node_modules/@tensorflow/tfjs-converter
> npm ERR! code EISGIT
> npm ERR! git /root/repo/node_modules/@tensorflow/tfjs-converter: Appears to be a git repo or submodule.
> npm ERR! git /root/repo/node_modules/@tensorflow/tfjs-converter
> npm ERR! git Refusing to remove it. Update manually,
> npm ERR! git or move it out of the way first.
> 
> any ideas?

I'm having this problem too. Have you tried manually removing its .git and seeing if your app still works?

**Comment by rmsparajuli** [comment]
this isn't best way but it works.

remove package-lock.json 
and then npm install

**Comment by manjunath1998** [comment]
rm -rf node_modules/*/.git/ 
this is a command right

**Comment by Atomo87** [comment]
Manually delete the seen react-native-safe-area module, and then run npm.
This will update the module. This happens when there is a mismatch between the react-native-safe-view-area module and the module it intends to install. Example, react-native-gesture-manipulator.

**Comment by ravics09** [comment]
> rm -rf node_modules/*/.git/

Its worked for me.

**Comment by FredericoVieira** [comment]
I have to do this two steps to work!
> Try it `rm -rf node_modules/*/.git/`. It works for me!
> remove package-lock.json

Thanks!

**Comment by Zoha131** [comment]
> rm -rf node_modules/*/.git/

1m silence for the windows users like me. :see_no_evil: :hear_no_evil: :speak_no_evil:

**Comment by iahmedbacha** [comment]
If still have this problem try: 
`rm -rf ../node_modules/**/*/.git/`

**Comment by iahmedbacha** [comment]
If still have this problem try:
`rm -rf node_modules/**/*/.git/`

**Comment by ilibilibom** [comment]
I tried 
```
rm -rf node_modules/*/.git/
```
and still getting the same error ....
I don't seem to have a .git directory in 
```
node_modules/react-native-safe-area-view
```

**Comment by iahmedbacha** [comment]
> I tried
> 
> ```
> rm -rf node_modules/*/.git/
> ```
> 
> and still getting the same error ....
> I don't seem to have a .git directory in
> 
> ```
> node_modules/react-native-safe-area-view
> ```

Try to clone the repo again (in another directory) and run npm install.

**Comment by ilibilibom** [comment]
> > I tried
> > ```
> > rm -rf node_modules/*/.git/
> > ```
> > 
> > 
> > and still getting the same error ....
> > I don't seem to have a .git directory in
> > ```
> > node_modules/react-native-safe-area-view
> > ```
> 
> Try to clone the repo again (in another directory) and run npm install.

How would this effect my project ?

**Comment by iahmedbacha** [comment]
> > > I tried
> > > ```
> > > rm -rf node_modules/*/.git/
> > > ```
> > > 
> > > 
> > > and still getting the same error ....
> > > I don't seem to have a .git directory in
> > > ```
> > > node_modules/react-native-safe-area-view
> > > ```
> > 
> > 
> > Try to clone the repo again (in another directory) and run npm install.
> 
> How would this effect my project ?

It will not effect your project since you are just cloning  it again.
Before you do that try to go to "./node_modules/react-native-safe-area-view/" and delete ./git directory manually.

**Comment by ilibilibom** [comment]
> > > > I tried
> > > > ```
> > > > rm -rf node_modules/*/.git/
> > > > ```
> > > > 
> > > > 
> > > > and still getting the same error ....
> > > > I don't seem to have a .git directory in
> > > > ```
> > > > node_modules/react-native-safe-area-view
> > > > ```
> > > 
> > > 
> > > Try to clone the repo again (in another directory) and run npm install.
> > 
> > 
> > How would this effect my project ?
> 
> It will not effect your project since you are just cloning it again.
> Before you do that try to go to "./node_modules/react-native-safe-area-view/" and delete ./git directory manually.

You can see in my first comment that I don't have a .got directory

**Comment by kirankbee** [comment]
i manually deleted .git folder and all the references to git in  package.json 
located under  react_native_safe_area_view folder, it worked for me .

**Comment by VishwaNandhu** [comment]
i manually remove
node_modules and package-lock.json 
then run command 
npm cache clean --force 
npm install --save 
its work for me .

**Comment by infinitbility** [comment]
> I tried
> 
> ```
> rm -rf node_modules/*/.git/
> ```
> 
> and still getting the same error ....
> I don't seem to have a .git directory in
> 
> ```
> node_modules/react-native-safe-area-view
> ```

Delete your `react-native-safe-area-view` from node modules

**Comment by yesIamFaded** [comment]
What does -rf stand for because I cant run the command on windows ... It tells me that it doesnt know the command -rf 

using windows 10

**Comment by kirankbee** [comment]
Sorry was on mac, on windows it should be simple  rmdir
-thanks
kirankumar

**Comment by yesIamFaded** [comment]
@kirankbee ok but somehow i still have the error..

**Comment by mkhoussid** [comment]
Running `npx yarn add react-native-safe-area-view` should fix it.
[SO link](https://stackoverflow.com/questions/61768202/npm-err-code-eisgit-react-native-safe-area-view?noredirect=1#comment109256831_61768202).

**Comment by yesIamFaded** [comment]
yh thats the fix got it from stack yesterday !!! @mkhoussid

**Comment by JiangWeixian** [comment]
@Irislm thanks, save my day
