### ISSUE TITLE
`getInset` flow type not defined

### ISSUE THREAD

**Issue by mmavko** [react-native-community/react-native-safe-area-view#74]
# Bug

One cannot use `getInset` separately when using Flow.

## Environment info

React native info output:

```bash
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 1.12 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 24, 27, 28
        Build Tools: 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: 0.14.4

## Steps To Reproduce

The following code will generate a Flow error: 

```js
// @flow

import {getInset} from 'react-native-safe-area-view';
```

Flow error: Cannot import `getInset` because there is no `getInset` export in `react-native-safe-area-view`. Flow(InferError)

**Comment by brentvatne** [comment]
hi! this function is gone now in 1.0

**Comment by avet-m** [comment]
@brentvatne  there is no getInset function for export in v1.0
`import { getInset } from 'react-native-safe-area-view'; `- not a function

**Comment by brentvatne** [comment]
i know! that's what i said! 😆 

> hi! this function is gone now in 1.0

**Comment by DonavanMartin** [comment]
import StaticSafeAreaInsets from 'react-native-static-safe-area-insets';
const bottomOffset = StaticSafeAreaInsets.safeAreaInsetsBottom;
