### ISSUE TITLE
iPad Pro 2nd gen shouldnt use SafeArea insets

### ISSUE THREAD

**Issue by viventus** [react-native-community/react-native-safe-area-view#86]
Only 3rd generation needs safe area insets, dont use window dimensions for detecting devices

**Comment by louisch** [comment]
I think it would be good if you could upload whatever props and such you are passing to your SafeAreaView (some example code)

**Comment by brentvatne** [comment]
this should be resolved in version 1.0 which was released today, thanks for reporting!
