### ISSUE TITLE
Missing exports on web version

### ISSUE THREAD

**Issue by brunolemos** [react-native-community/react-native-safe-area-view#88]
# Bug

The [index.web.js](https://github.com/react-native-community/react-native-safe-area-view/blob/master/src/index.web.js) file only exports `default`, it should also export `useSafeArea`, `SafeAreaProvider`, `SafeAreaConsumer` and `SafeAreaContext`.

**Comment by brentvatne** [comment]
this library is deprecated, use react-native-safe-area-context instead :)
