### ISSUE TITLE
Preserves the space for the status bar on the iPad when it should not

### ISSUE THREAD

**Issue by RoosterKelly** [react-native-community/react-native-safe-area-view#9]
If you have an app that is fullscreen and disables the status bar, safe area view still reserves space for the status bar.

If the status bar is disabled, statusBarHeight() should return 0. https://github.com/react-community/react-native-safe-area-view/blob/7de5b3fc484df3cafdca1ec0cdda6df7e6d99259/index.js#L60-L62

**Comment by davepack** [comment]
Thanks @RoosterKelly, could you make a PR to fix this?

**Comment by pampang** [comment]
@davepack I've make a pull request about this.
Can you review it? Thanks. #14

**Comment by davepack** [comment]
@RoosterKelly, the PR by @pampang has been merged and released as v0.4.0. The fix is to add `forceInset={{ top: 'never' }}` to the SafeAreaView. Thanks for the help @pampang.
