### ISSUE TITLE
Support forwarding a ref in the "ref" prop + setNativeProps

### ISSUE THREAD

**Issue by brunolemos** [react-native-community/react-native-safe-area-view#90]
# Bug

The base API from `SafeAreaView` should be the same from `react-native`, I noticed it's diverging on the `ref`. React Native supports passing a `ref={ref}` and calling `ref.current.setNativeProps()`, while `react-native-safe-area-view` has a private field `_view` for that.

## Environment info

Library version: 1.0.0-alpha.0

**Comment by brentvatne** [comment]
this library is deprecated, use react-native-safe-area-context instead :)
