### ISSUE TITLE
support for expo 34

### ISSUE THREAD

**Issue by theZulqarnain** [react-native-community/react-native-safe-area-view#93]
in docs mentioned that it will support EXPO SDK 35, but officially EXPO SDK 34 only. when I'm using in EXPO 34 getting linking error.is there any way without detaching I can use **react-native-safe-area-view** Lib.

>Invariant Violation: requireNativeComponent: "RNCSafeAreaView" was not found in the UIManager.

**Comment by brentvatne** [comment]
don't use 1.0.0-alpha, use ^0.14.

**Comment by brentvatne** [comment]
expo sdk 35 is released and so is version 1.0.0 of this lib
