### ISSUE TITLE
forceInset={{ top: 'never' }} not working on Android

### ISSUE THREAD

**Issue by dotpegaso** [react-native-community/react-native-safe-area-view#97]
```
"react-native": "0.61.3",
"react-native-safe-area-context": "^0.6.0",
"react-native-safe-area-view": "^1.0.0",
```
Device: `Xiaomi Mi A2 Lite`

Works fine on iOS.

**Comment by enkechan** [comment]
Japanese Mi fans?

**Comment by minayaleon** [comment]
I've same problem

**Comment by minayaleon** [comment]
> ```
> "react-native": "0.61.3",
> "react-native-safe-area-context": "^0.6.0",
> "react-native-safe-area-view": "^1.0.0",
> ```
> 
> Device: `Xiaomi Mi A2 Lite`
> 
> Works fine on iOS.

Did you find any solution?

**Comment by haideralishah** [comment]
@dotpegaso have you found the solution?
please share 
I m facing same problem.

**Comment by dotpegaso** [comment]
@minayaleon @haideralishah couldn't find any solution yet, it looks like a native lack of support, idk.

**Comment by brentvatne** [comment]
please use SafeAreaView from https://github.com/th3rdwave/react-native-safe-area-context instead
