### ISSUE TITLE
Unstable behaviour with react-native-navigation tabs

### ISSUE THREAD

**Issue by mifi** [react-native-community/react-native-safe-area-view#98]
# Bug

When used with react navigation tab bars (inside the tab views), sometimes when switching tabs back and forth, the safe area inset disappears. Easy to reproduce with Fast Refresh enabled: 
1. Have two tabs, both with safeareaview inside their views.
2. Test on iOS simulator, iPhone X (notch) or iPhone 6 (status bar)
2. Open main tab and observe safearea view padding
3. save js file of other tab in editor and observe code being reloaded
4. Switch to the other tab that has been reloaded
5. observe that the top inset is missing

Note that when using `react-native-safe-area-context` and logging the insets using `useSafeArea` hook, the values are reported correctly even though rendered without insets in SafeAreaView from `react-native-safe-area-view`. And since this module is using react-native-safe-area-context, I'm thinking there is something wrong with the code in this module. **Using SafeAreaView exported from react-native-safe-area-context does not exhibit this problem.**

## Environment info

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 564.35 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.11.1 - ~/tools/node-v12.11.1-darwin-x64/bin/node
    Yarn: 1.19.0 - ~/tools/node-v12.11.1-darwin-x64/bin/yarn
    npm: 6.11.3 - ~/tools/node-v12.11.1-darwin-x64/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 16, 26, 28
      Build Tools: 26.0.3, 28.0.2, 28.0.3
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.10.2 => 16.10.2 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native: 0.61.2
```

Library version: 1.0.0
context version 0.4.1
    "react-navigation-tabs": "^2.5.5",
    "react-navigation": "^4.0.10",

## Reproducible sample code

Can add code soon

**Comment by kdenz** [comment]
Same issue here, my dependencies: 
```
"@react-navigation/bottom-tabs": "^5.0.0-alpha.22",
"@react-navigation/core": "^5.0.0-alpha.23",
"@react-navigation/native": "^5.0.0-alpha.19",
"@react-navigation/stack": "^5.0.0-alpha.37",
"react-native-safe-area-context": "^0.6.1",
"react-native-safe-area-view": "^1.0.0",
```
Using the `SafeAreaView` from `react-native-safe-area-context` works fine.

**Comment by brentvatne** [comment]
we built this library specifically with react-navigation in mind. also, this library will be deprecated soon, i recommend using https://github.com/th3rdwave/react-native-safe-area-context instead.
