### ISSUE TITLE
What does this module give that react-native-safe-area-context hasn't?

### ISSUE THREAD

**Issue by mifi** [react-native-community/react-native-safe-area-view#99]
# Question

Since this module uses react-native-safe-area-context to get insets, and react-native-safe-area-context also has a SafeAreaView, why should I use this one when this one has more complicated (and error prone) logic built on top? Maybe we can add some clarification in README?

**Comment by gilsonviana** [comment]
I found this repo by reading the React Navigation docs and frankly I was asking myself the same question as @mifi.

**Comment by luancurti** [comment]
@gilsonviana @mifi This repository exists because `react-native-safe-area-context` is specific for `Android` and `react-native SafeAreaView` component is specific for `iOS 11+` this component works on both platforms.

**Comment by mifi** [comment]
react-native-safe-area-context is not android only. Works on android, ios and web.
From what i found out, the main difference between the two is that react-native-safe-area-view continously detects if the view is underneath a notch and adds a padding accordingly on every redraw eg when moving/scrolling the element. react-native-safe-area-context only allows a static offset depending on device notches. However react-native-safe-area-view does not work properly with react-navigation in my experience. (Modal in prticular) so i ended up using the other.

See bug: https://github.com/react-native-community/react-native-safe-area-view/issues/98

**Comment by brentvatne** [comment]
nothing. you don't need this library now.

it existed prior to safe-area-context and we worked with the creator of that lib and now it is a much better solution than this. at the time you wrote this, it provided a safeareaview that would detect the position of the view on the screen and then use context to inset appropriately, but now safe-area-context does that better, so this library is not necessary. we'll deprecate soon
